[rt] Revert "percpu: include irqflags.h for raw_local_irq_save()"
Building the rt-amd64 flavour now fails with the following error:

    .../include/linux/percpu-defs.h:49:34: error: 'PER_CPU_BASE_SECTION' undeclared here (not in a function); did you mean 'PER_CPU_FIRST_SECTION'?

This is due to an #include loop on x86:

    <asm/percpu.h>
     -> <linux/irqflags.h>
         -> <asm/irqflags.h>
             -> <asm/nospec-branch.h>
                 -> <asm/percpu.h>

The loop doesn't exist in any stable or stable-rt branch, but:

- The reverted patch adds <asm/percpu.h> -> <linux/irqflags.h>
- 4.19.266 added <asm/nospec-branch.h> -> <asm/percpu.h>

Neither upstream nor any other maintained stable-rt branch has this
patch, and the build succeeds without it, so remove it here as well.