debian/lib/python/debian_linux/abi.py: Add one missing string replacement
While adding the support for namespaces, the format string missed one
string replacement to write out in the ABI reference file and will cause

	Updating ABI for arch amd64, featureset none, flavour amd64: FAILED!
	Traceback (most recent call last):
	  File "debian/bin/abiupdate.py", line 192, in update_flavour
	    self.save_abi(version_abi, abi, arch, featureset, flavour)
	  File "debian/bin/abiupdate.py", line 159, in save_abi
	    symbols.write(open(out, 'w'))
	  File "/src/kernel-team/linux/linux/debian/bin/debian_linux/abi.py", line 44, in write
	    (s.version, s.name, s.namespace, s.module, s.export))
	TypeError: not all arguments converted during string formatting

Fixes: 676810be3442 ("debian/lib/python/debian_linux/abi.py: Add support for namespaces")